### ISSUE TITLE
Happend once before the bot doesnt recognise that its playing music

### ISSUE THREAD

**Issue by dragonsynmeli** [SJ-Plan-B/Plan-Bot#194]
## Describe the bug
The bug happend when i was trying to play a song using the command
the volume change only produced messages that its not playing anything even tho it was playing the songs.
will report if happend again maybe with screen recording
## To Reproduce
unfortunatly this only happen once and that seemingly random.

## Expected behavior
that it recognises that it plays the music and changes volume 

## Screenshots

![Screenshot 2023-01-15 193325](https://user-images.githubusercontent.com/122746545/212560201-bf5e4aaf-3675-432b-880a-0bfbe15923da.png)

## Software Version (please complete the following information):
No fucking idea ask yoshi or die fucking ente

## Additional context
i like big butts and cannot lie

**Comment by XCOYoshi** [comment]
Adresst in discord-player issue #[1487](https://github.com/Androz2091/discord-player/issues/1487)
